### ISSUE TITLE
@server -> prefix  parsing failed  v1.1.1

### ISSUE THREAD

**Issue by fyyang** [zeromicro/goctl-intellij#17]
version: v1.1.1

<img width="418" alt="image" src="https://user-images.githubusercontent.com/10858992/167535377-b1864e03-9fc5-47d1-aedc-9cfe8323ac3d.png">

I hope to add another one that supports @ server - > ` swtags`

**Comment by fyyang** [comment]
安哥已经6天了

**Comment by anqiansong** [comment]
It has been fixed  on release [v1.1.2](https://github.com/zeromicro/goctl-intellij/releases/tag/v1.1.2)
