### ISSUE TITLE
请问插件是否支持指定模板路径呢?

### ISSUE THREAD

**Issue by wabzsy** [zeromicro/goctl-intellij#6]
我对goctl的template做了一些修改, 在命令行下可以用--home参数指定自定义模板的位置, 但是在intellij插件里好像用的还是默认的模板.
还有就是是否可以配置goctl的 --style 参数呢?

**Comment by anqiansong** [comment]
暂时还不支持，不过可以考虑哈

**Comment by zhaorx** [comment]
在哪里配置goctl的 --style 参数? 每次都需要修改
